-- =============================================================
-- Datalyze – seed data
-- Intentionally empty: users are created via the signup flow.
-- =============================================================
