"""Knowledge Graph Builder Agent — guarded, heavy_alt.

Emits Neo4j-style node/edge bundles for client-side rendering (no DB required).
"""

from __future__ import annotations

from typing import Any

from services.agents.shared_prompts import build_system_prompt

AGENT_ID = "knowledge_graph_builder"
AGENT_NAME = "Knowledge Graph Builder Agent"
STRICTNESS = "guarded"
TOKEN_BUDGET = 1200

SYSTEM_PROMPT = build_system_prompt(
    role=AGENT_NAME,
    agent_id=AGENT_ID,
    scope_boundary="entity relationship graph construction",
    strictness=STRICTNESS,
    token_budget=TOKEN_BUDGET,
    core_instructions=(
        "You build an entity–relationship graph from the aggregated corpus so it can be "
        "imported or mirrored in Neo4j and rendered in the web viewer.\n\n"
        "Neo4j-oriented rules (client-side / offline use):\n"
        "- Each node uses a unique string `id` (stable, lowercase_snake_case). That id is the "
        "join key for edges and clusters.\n"
        "- `type` is the node category (maps to a Neo4j label suggestion: Metric, Company, "
        "Person, Product, Date, Location, Concept, etc.).\n"
        "- `label` is the human-readable title shown in the UI.\n"
        "- Optional `value` holds a scalar fact when the node represents a metric or number.\n"
        "- `context` (REQUIRED): short quote or paraphrase of what the aggregator/corpus "
        "provided as evidence for this entity.\n"
        "- `insights` (REQUIRED): array of short analytic notes about this node generated by "
        "you; use [] if none.\n\n"
        "Edges:\n"
        "- `source` and `target` MUST equal existing node `id` values.\n"
        "- `relationship` is the relationship type name (e.g. correlated_with, drives, "
        "part_of, mentions).\n"
        "- `strength` is 0.0–1.0 optional confidence/strength for the link.\n\n"
        "Clusters:\n"
        "- Group related nodes for UI bundling: {\"name\": \"...\", \"node_ids\": [\"id1\", ...]}\n\n"
        "Output schema:\n"
        "{\n"
        '  "nodes": [\n'
        "    {\n"
        '      "id": "revenue_q1",\n'
        '      "label": "Q1 Revenue",\n'
        '      "type": "metric",\n'
        '      "value": 820000,\n'
        '      "context": "Evidence from corpus ...",\n'
        '      "insights": ["Grew vs prior quarter", "..."]\n'
        "    }\n"
        "  ],\n"
        '  "edges": [\n'
        "    {\n"
        '      "source": "revenue_q1",\n'
        '      "target": "marketing_spend",\n'
        '      "relationship": "correlated_with",\n'
        '      "strength": 0.78\n'
        "    }\n"
        "  ],\n"
        '  "clusters": [{"name": "Financial Metrics", "node_ids": ["revenue_q1", "..."]}],\n'
        '  "chart_suggestions": ["knowledge_graph_network", "cluster_map"]\n'
        "}\n\n"
        "Minimum depth: at least 5 nodes and 4 edges when the corpus supports it; otherwise "
        "return fewer but keep schema valid. JSON only."
    ),
)

OUTPUT_SCHEMA = {
    "required": ["nodes", "edges", "clusters", "chart_suggestions"],
    "optional": ["node_types", "edge_types"],
}


def build_agent(llm: Any) -> Any:
    from crewai import Agent

    return Agent(
        role=AGENT_NAME,
        goal="Build a Neo4j-compatible typed graph with context and per-node insights.",
        backstory=SYSTEM_PROMPT,
        llm=llm,
        verbose=False,
    )


def build_task(agent: Any, context_tasks: list[Any] | None = None) -> Any:
    from crewai import Task

    return Task(
        description=(
            "From the aggregated corpus, extract entities and relationships. "
            "Every node must include context (corpus evidence) and insights (analysis). "
            "Edges must reference node ids; add clusters and chart_suggestions. "
            "Return ONLY a JSON object matching the required schema."
        ),
        expected_output="JSON object with keys: nodes, edges, clusters, chart_suggestions",
        agent=agent,
        context=context_tasks or [],
    )
