"""PDF report generation service for pipeline run exports."""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from io import BytesIO
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger("export_pdf")

BG_DARK = colors.HexColor("#1e293b")
BG_CARD = colors.HexColor("#334155")
BG_TABLE_HEADER = colors.HexColor("#0f172a")
BG_TABLE_ROW_ALT = colors.HexColor("#1e293b")
BG_TABLE_ROW = colors.HexColor("#273548")
TEXT_WHITE = colors.HexColor("#f1f5f9")
TEXT_MUTED = colors.HexColor("#94a3b8")
ACCENT_BLUE = colors.HexColor("#38bdf8")
ACCENT_GREEN = colors.HexColor("#4ade80")
ACCENT_AMBER = colors.HexColor("#fbbf24")
ACCENT_RED = colors.HexColor("#f87171")

PAGE_W, PAGE_H = letter
MARGIN = 0.6 * inch
CONTENT_W = PAGE_W - 2 * MARGIN


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "PDFTitle", parent=base["Title"],
            fontSize=22, leading=28, textColor=TEXT_WHITE,
            spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "PDFSubtitle", parent=base["Normal"],
            fontSize=10, leading=14, textColor=TEXT_MUTED,
            spaceAfter=12,
        ),
        "section": ParagraphStyle(
            "PDFSection", parent=base["Heading2"],
            fontSize=14, leading=18, textColor=ACCENT_BLUE,
            spaceBefore=18, spaceAfter=8,
        ),
        "body": ParagraphStyle(
            "PDFBody", parent=base["Normal"],
            fontSize=10, leading=14, textColor=TEXT_WHITE,
            spaceAfter=6,
        ),
        "body_muted": ParagraphStyle(
            "PDFBodyMuted", parent=base["Normal"],
            fontSize=9, leading=13, textColor=TEXT_MUTED,
            spaceAfter=4,
        ),
        "bullet": ParagraphStyle(
            "PDFBullet", parent=base["Normal"],
            fontSize=10, leading=14, textColor=TEXT_WHITE,
            leftIndent=16, spaceAfter=3,
        ),
        "footer": ParagraphStyle(
            "PDFFooter", parent=base["Normal"],
            fontSize=7, leading=10, textColor=TEXT_MUTED,
        ),
    }


def _dark_bg(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(BG_DARK)
    canvas.rect(0, 0, PAGE_W, PAGE_H, fill=True, stroke=False)
    # footer
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
    canvas.setFillColor(TEXT_MUTED)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(MARGIN, 0.35 * inch, f"Generated by Datalyze  |  {now}")
    canvas.drawRightString(PAGE_W - MARGIN, 0.35 * inch, f"Page {doc.page}")
    canvas.restoreState()


def _make_table(headers: list[str], rows: list[list[str]], col_widths: list[float] | None = None) -> Table:
    s = _styles()
    header_cells = [Paragraph(f"<b>{h}</b>", s["body"]) for h in headers]
    body_rows = [
        [Paragraph(str(cell), s["body_muted"]) for cell in row]
        for row in rows
    ]
    data = [header_cells, *body_rows]

    tbl = Table(data, colWidths=col_widths, repeatRows=1)
    style_cmds: list[Any] = [
        ("BACKGROUND", (0, 0), (-1, 0), BG_TABLE_HEADER),
        ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_WHITE),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#475569")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]
    for i in range(1, len(data)):
        bg = BG_TABLE_ROW if i % 2 == 0 else BG_TABLE_ROW_ALT
        style_cmds.append(("BACKGROUND", (0, i), (-1, i), bg))
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def _read_agent_outputs(run_dir: str) -> dict[str, dict[str, Any]]:
    """Read individual agent output envelopes from the run directory."""
    agent_dir = Path(run_dir) / "context" / "agent_outputs"
    outputs: dict[str, dict[str, Any]] = {}
    if not agent_dir.is_dir():
        return outputs
    for child in agent_dir.iterdir():
        if not child.is_dir():
            continue
        agent_id = child.name
        steps = sorted(child.glob("step_*.json"), key=lambda p: p.name)
        if not steps:
            continue
        try:
            data = json.loads(steps[-1].read_text(encoding="utf-8"))
            outputs[agent_id] = data
        except (json.JSONDecodeError, OSError):
            pass
    return outputs


def _extract_parsed_output(envelope: dict[str, Any]) -> dict[str, Any]:
    """Pull structured data from an agent envelope's artifacts."""
    for artifact in envelope.get("artifacts", []):
        if isinstance(artifact, dict):
            parsed = artifact.get("parsed_output") or artifact.get("data")
            if isinstance(parsed, dict):
                return parsed
            if isinstance(artifact.get("content"), dict):
                return artifact["content"]
    if isinstance(envelope.get("summary"), dict):
        return envelope["summary"]
    return {}


def _priority_color(priority: str) -> str:
    p = str(priority).lower()
    if "high" in p or "critical" in p:
        return ACCENT_RED.hexval()
    if "medium" in p or "moderate" in p:
        return ACCENT_AMBER.hexval()
    return ACCENT_GREEN.hexval()


async def generate_pdf_report(run_slug: str, run_dir: str, run_data: dict) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=0.6 * inch,
    )
    s = _styles()
    elements: list[Any] = []

    report: dict[str, Any] = {}
    report_path = Path(run_dir) / "final_report.json"
    if report_path.is_file():
        try:
            report = json.loads(report_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass

    agent_outputs = _read_agent_outputs(run_dir)
    exec_envelope = agent_outputs.get("executive_summary", {})
    exec_data = _extract_parsed_output(exec_envelope)
    insight_envelope = agent_outputs.get("insight_generation", {})
    insight_data = _extract_parsed_output(insight_envelope)
    trend_envelope = agent_outputs.get("trend_forecasting", {})
    trend_data = _extract_parsed_output(trend_envelope)
    swot_envelope = agent_outputs.get("swot_analysis", {})
    swot_data = _extract_parsed_output(swot_envelope)

    # ── Header ──────────────────────────────────────────────
    elements.append(Paragraph("DATALYZE", s["title"]))
    elements.append(Paragraph("AI-Powered Business Intelligence Report", s["subtitle"]))
    elements.append(Spacer(1, 4))

    track = run_data.get("track") or report.get("track") or "—"
    status = run_data.get("status") or report.get("status") or "—"
    started = run_data.get("started_at") or "—"
    ended = run_data.get("ended_at") or "—"
    finalized = report.get("finalized_at", "")

    meta_rows = [
        ["Run", run_slug, "Track", track.replace("_", " ").title()],
        ["Status", status.replace("_", " ").title(), "Started", started],
        ["Ended", ended, "Finalized", finalized[:19] if finalized else "—"],
    ]
    meta_tbl = Table(meta_rows, colWidths=[0.8 * inch, 2.2 * inch, 0.8 * inch, 2.2 * inch])
    meta_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BG_CARD),
        ("TEXTCOLOR", (0, 0), (-1, -1), TEXT_WHITE),
        ("TEXTCOLOR", (0, 0), (0, -1), TEXT_MUTED),
        ("TEXTCOLOR", (2, 0), (2, -1), TEXT_MUTED),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#475569")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(meta_tbl)
    elements.append(Spacer(1, 14))

    # ── Executive Summary ───────────────────────────────────
    headline = exec_data.get("headline") or exec_envelope.get("summary") or report.get("summary") or ""
    if headline:
        elements.append(Paragraph("Executive Summary", s["section"]))
        elements.append(Paragraph(str(headline), s["body"]))

        situation = exec_data.get("situation_overview")
        if situation:
            elements.append(Spacer(1, 4))
            elements.append(Paragraph(str(situation), s["body_muted"]))

        for finding in (exec_data.get("key_findings") or []):
            elements.append(Paragraph(f"• {finding}", s["bullet"]))

        elements.append(Spacer(1, 6))

    # ── Risk Highlights ─────────────────────────────────────
    risks = exec_data.get("risk_highlights") or []
    if risks:
        elements.append(Paragraph("Risk Highlights", s["section"]))
        for r in risks:
            elements.append(Paragraph(f"⚠ {r}", s["bullet"]))
        elements.append(Spacer(1, 6))

    # ── KPI / Forecast Summary ──────────────────────────────
    forecasts = trend_data.get("forecasts") or []
    if forecasts:
        elements.append(Paragraph("KPI / Forecast Summary", s["section"]))
        kpi_headers = ["KPI / Metric", "Forecast", "Details"]
        kpi_rows: list[list[str]] = []
        for fc in forecasts[:15]:
            if isinstance(fc, dict):
                kpi_rows.append([
                    str(fc.get("metric") or fc.get("name") or fc.get("kpi", "—")),
                    str(fc.get("forecast") or fc.get("value") or fc.get("prediction", "—")),
                    str(fc.get("details") or fc.get("trend") or fc.get("direction", "")),
                ])
            else:
                kpi_rows.append([str(fc), "", ""])
        if kpi_rows:
            elements.append(_make_table(kpi_headers, kpi_rows, [1.8 * inch, 2.0 * inch, 2.4 * inch]))
            elements.append(Spacer(1, 10))

    # ── Insights ────────────────────────────────────────────
    insights_list = insight_data.get("insights") or []
    if insights_list:
        elements.append(Paragraph("Key Insights", s["section"]))
        for ins in insights_list[:10]:
            if isinstance(ins, dict):
                label = ins.get("title") or ins.get("insight") or ins.get("description", "")
                elements.append(Paragraph(f"• {label}", s["bullet"]))
            else:
                elements.append(Paragraph(f"• {ins}", s["bullet"]))
        elements.append(Spacer(1, 6))

    # ── Recommendations ─────────────────────────────────────
    recommendations = insight_data.get("recommendations") or exec_data.get("next_actions") or []
    if recommendations:
        elements.append(Paragraph("Recommendations", s["section"]))
        rec_headers = ["Action", "Priority", "Confidence"]
        rec_rows: list[list[str]] = []
        for rec in recommendations[:15]:
            if isinstance(rec, dict):
                action = str(rec.get("action") or rec.get("recommendation") or rec.get("title", "—"))
                priority = str(rec.get("priority", "—"))
                conf = rec.get("confidence")
                conf_str = f"{float(conf):.0%}" if conf is not None else "—"
                rec_rows.append([action, priority, conf_str])
            else:
                rec_rows.append([str(rec), "—", "—"])
        if rec_rows:
            elements.append(_make_table(rec_headers, rec_rows, [3.6 * inch, 1.2 * inch, 1.4 * inch]))
            elements.append(Spacer(1, 10))

    # ── SWOT Summary ────────────────────────────────────────
    has_swot = any(swot_data.get(q) for q in ("strengths", "weaknesses", "opportunities", "threats"))
    if has_swot:
        elements.append(Paragraph("SWOT Analysis", s["section"]))
        for quadrant, label in [
            ("strengths", "Strengths"),
            ("weaknesses", "Weaknesses"),
            ("opportunities", "Opportunities"),
            ("threats", "Threats"),
        ]:
            items = swot_data.get(quadrant) or []
            if items:
                elements.append(Paragraph(f"<b>{label}</b>", s["body"]))
                for item in items[:5]:
                    txt = item if isinstance(item, str) else str(item.get("description", item) if isinstance(item, dict) else item)
                    elements.append(Paragraph(f"• {txt}", s["bullet"]))
                elements.append(Spacer(1, 4))
        elements.append(Spacer(1, 6))

    # ── Confidence Breakdown ────────────────────────────────
    conf_rows: list[list[str]] = []
    for aid, env in agent_outputs.items():
        conf = env.get("confidence")
        if conf is not None:
            st = env.get("status", "—")
            conf_rows.append([aid.replace("_", " ").title(), st, f"{float(conf):.0%}"])
    exec_conf = exec_data.get("confidence_statement")
    if isinstance(exec_conf, dict):
        overall = exec_conf.get("overall_confidence")
        basis = exec_conf.get("basis", "")
        if overall is not None:
            conf_rows.insert(0, ["Overall (Executive)", basis[:60] if basis else "—", f"{float(overall):.0%}"])

    if conf_rows:
        elements.append(Paragraph("Confidence Breakdown", s["section"]))
        elements.append(_make_table(
            ["Agent / Metric", "Status / Basis", "Confidence"],
            conf_rows,
            [2.6 * inch, 2.2 * inch, 1.4 * inch],
        ))
        elements.append(Spacer(1, 10))

    # ── Agent Activity Log ──────────────────────────────────
    activity = run_data.get("agent_activity") or []
    if activity:
        elements.append(Paragraph("Agent Activity Log", s["section"]))
        act_headers = ["Agent", "Stage", "Status", "Message"]
        act_rows: list[list[str]] = []
        for row in activity[:30]:
            if isinstance(row, dict):
                act_rows.append([
                    str(row.get("agent_id", "—")).replace("_", " ").title(),
                    str(row.get("stage", "—")),
                    str(row.get("status", "—")),
                    str(row.get("message", ""))[:80],
                ])
        if act_rows:
            elements.append(_make_table(act_headers, act_rows, [1.6 * inch, 1.0 * inch, 0.9 * inch, 2.7 * inch]))
            elements.append(Spacer(1, 10))

    # ── Warnings & Fix Suggestions ──────────────────────────
    warnings = report.get("warnings") or []
    fixes = report.get("fix_suggestions") or []
    if warnings or fixes:
        elements.append(Paragraph("Warnings &amp; Suggestions", s["section"]))
        for w in warnings[:10]:
            elements.append(Paragraph(f"⚠ {w}", s["bullet"]))
        for f in fixes[:10]:
            elements.append(Paragraph(f"→ {f}", s["bullet"]))
        elements.append(Spacer(1, 6))

    # ── Pipeline Log (last entries) ─────────────────────────
    plog = run_data.get("pipeline_log") or []
    if plog:
        elements.append(Paragraph("Pipeline Log (Recent)", s["section"]))
        for entry in plog[-10:]:
            elements.append(Paragraph(str(entry)[:120], s["body_muted"]))
        elements.append(Spacer(1, 8))

    # ── Build ───────────────────────────────────────────────
    if not elements:
        elements.append(Paragraph("No report data available for this run.", s["body"]))

    doc.build(elements, onFirstPage=_dark_bg, onLaterPages=_dark_bg)
    return buf.getvalue()
