"""PDF report generation service for pipeline run exports."""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from io import BytesIO
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image as RLImage,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from services.export_common import (
    extract_parsed_output,
    merge_agent_results,
    merge_replay_agent_results,
    read_agent_outputs,
    section_dict,
)
from services.export_html import collect_figures_for_pdf, knowledge_graph_node_rows

logger = logging.getLogger("export_pdf")

BG_DARK = colors.HexColor("#1e293b")
BG_CARD = colors.HexColor("#334155")
BG_TABLE_HEADER = colors.HexColor("#0f172a")
BG_TABLE_ROW_ALT = colors.HexColor("#1e293b")
BG_TABLE_ROW = colors.HexColor("#273548")
TEXT_WHITE = colors.HexColor("#f1f5f9")
TEXT_MUTED = colors.HexColor("#94a3b8")
ACCENT_BLUE = colors.HexColor("#38bdf8")
ACCENT_GREEN = colors.HexColor("#4ade80")
ACCENT_AMBER = colors.HexColor("#fbbf24")
ACCENT_RED = colors.HexColor("#f87171")

PAGE_W, PAGE_H = letter
MARGIN = 0.6 * inch
CONTENT_W = PAGE_W - 2 * MARGIN


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "PDFTitle", parent=base["Title"],
            fontSize=22, leading=28, textColor=TEXT_WHITE,
            spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "PDFSubtitle", parent=base["Normal"],
            fontSize=10, leading=14, textColor=TEXT_MUTED,
            spaceAfter=12,
        ),
        "section": ParagraphStyle(
            "PDFSection", parent=base["Heading2"],
            fontSize=14, leading=18, textColor=ACCENT_BLUE,
            spaceBefore=18, spaceAfter=8,
        ),
        "body": ParagraphStyle(
            "PDFBody", parent=base["Normal"],
            fontSize=10, leading=14, textColor=TEXT_WHITE,
            spaceAfter=6,
        ),
        "body_muted": ParagraphStyle(
            "PDFBodyMuted", parent=base["Normal"],
            fontSize=9, leading=13, textColor=TEXT_MUTED,
            spaceAfter=4,
        ),
        "bullet": ParagraphStyle(
            "PDFBullet", parent=base["Normal"],
            fontSize=10, leading=14, textColor=TEXT_WHITE,
            leftIndent=16, spaceAfter=3,
        ),
        "footer": ParagraphStyle(
            "PDFFooter", parent=base["Normal"],
            fontSize=7, leading=10, textColor=TEXT_MUTED,
        ),
    }


def _dark_bg(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(BG_DARK)
    canvas.rect(0, 0, PAGE_W, PAGE_H, fill=True, stroke=False)
    # footer
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
    canvas.setFillColor(TEXT_MUTED)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(MARGIN, 0.35 * inch, f"Generated by Datalyze  |  {now}")
    canvas.drawRightString(PAGE_W - MARGIN, 0.35 * inch, f"Page {doc.page}")
    canvas.restoreState()


def _make_table(headers: list[str], rows: list[list[str]], col_widths: list[float] | None = None) -> Table:
    s = _styles()
    header_cells = [Paragraph(f"<b>{h}</b>", s["body"]) for h in headers]
    body_rows = [
        [Paragraph(str(cell), s["body_muted"]) for cell in row]
        for row in rows
    ]
    data = [header_cells, *body_rows]

    tbl = Table(data, colWidths=col_widths, repeatRows=1)
    style_cmds: list[Any] = [
        ("BACKGROUND", (0, 0), (-1, 0), BG_TABLE_HEADER),
        ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_WHITE),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#475569")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]
    for i in range(1, len(data)):
        bg = BG_TABLE_ROW if i % 2 == 0 else BG_TABLE_ROW_ALT
        style_cmds.append(("BACKGROUND", (0, i), (-1, i), bg))
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def _priority_color(priority: str) -> str:
    p = str(priority).lower()
    if "high" in p or "critical" in p:
        return ACCENT_RED.hexval()
    if "medium" in p or "moderate" in p:
        return ACCENT_AMBER.hexval()
    return ACCENT_GREEN.hexval()


async def generate_pdf_report(
    run_slug: str,
    run_dir: str,
    run_data: dict,
    replay_payload: dict[str, Any] | None = None,
) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=0.6 * inch,
    )
    s = _styles()
    elements: list[Any] = []

    report: dict[str, Any] = {}
    report_path = Path(run_dir) / "final_report.json"
    if report_path.is_file():
        try:
            report = json.loads(report_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass

    ar = merge_replay_agent_results(replay_payload or {})
    if not ar:
        ar = merge_agent_results(replay_payload or {}, run_dir)
    agent_outputs = read_agent_outputs(run_dir)

    def merged_section(key: str) -> dict[str, Any]:
        d = section_dict(ar, key)
        if d:
            return d
        return extract_parsed_output(agent_outputs.get(key, {}))

    exec_envelope = agent_outputs.get("executive_summary", {})
    exec_data = merged_section("executive_summary")
    insight_data = merged_section("insight_generation")
    trend_data = merged_section("trend_forecasting")
    swot_data = merged_section("swot_analysis")

    # ── Header ──────────────────────────────────────────────
    elements.append(Paragraph("DATALYZE", s["title"]))
    elements.append(Paragraph("AI-Powered Business Intelligence Report", s["subtitle"]))
    elements.append(Spacer(1, 4))

    track = run_data.get("track") or report.get("track") or "—"
    status = run_data.get("status") or report.get("status") or "—"
    started = run_data.get("started_at") or "—"
    ended = run_data.get("ended_at") or "—"
    finalized = report.get("finalized_at", "")

    meta_rows = [
        ["Run", run_slug, "Track", track.replace("_", " ").title()],
        ["Status", status.replace("_", " ").title(), "Started", started],
        ["Ended", ended, "Finalized", finalized[:19] if finalized else "—"],
    ]
    meta_tbl = Table(meta_rows, colWidths=[0.8 * inch, 2.2 * inch, 0.8 * inch, 2.2 * inch])
    meta_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BG_CARD),
        ("TEXTCOLOR", (0, 0), (-1, -1), TEXT_WHITE),
        ("TEXTCOLOR", (0, 0), (0, -1), TEXT_MUTED),
        ("TEXTCOLOR", (2, 0), (2, -1), TEXT_MUTED),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#475569")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(meta_tbl)
    elements.append(Spacer(1, 14))

    # ── Executive Summary ───────────────────────────────────
    headline = exec_data.get("headline") or exec_envelope.get("summary") or report.get("summary") or ""
    if headline:
        elements.append(Paragraph("Executive Summary", s["section"]))
        elements.append(Paragraph(str(headline), s["body"]))

        situation = exec_data.get("situation_overview")
        if situation:
            elements.append(Spacer(1, 4))
            elements.append(Paragraph(str(situation), s["body_muted"]))

        for finding in (exec_data.get("key_findings") or []):
            elements.append(Paragraph(f"• {finding}", s["bullet"]))

        elements.append(Spacer(1, 6))

    # ── Risk Highlights ─────────────────────────────────────
    risks = exec_data.get("risk_highlights") or []
    if risks:
        elements.append(Paragraph("Risk Highlights", s["section"]))
        for r in risks:
            elements.append(Paragraph(f"⚠ {r}", s["bullet"]))
        elements.append(Spacer(1, 6))

    # ── Charts (static images via Kaleido / Plotly) ─────────
    track_for_charts = str(run_data.get("track") or report.get("track") or "")
    try:
        fig_pairs = collect_figures_for_pdf(track_for_charts, ar)
        if fig_pairs:
            elements.append(Paragraph("Charts &amp; visualizations", s["section"]))
            elements.append(
                Paragraph(
                    "Figures mirror the in-app analysis. The knowledge graph section includes "
                    "a node detail table (like the side panel in the app).",
                    s["body_muted"],
                )
            )
            elements.append(Spacer(1, 6))
            import plotly.io as pio

            for title, fig in fig_pairs:
                try:
                    png = pio.to_image(fig, format="png", width=1100, height=620, engine="kaleido")
                except Exception as chart_err:
                    logger.warning("PDF chart export failed (%s): %s", title, chart_err)
                    elements.append(
                        Paragraph(f"{title} — chart unavailable ({chart_err})", s["body_muted"])
                    )
                    elements.append(Spacer(1, 8))
                    continue
                bio = BytesIO(png)
                bio.seek(0)
                img_w = CONTENT_W
                img_h = img_w * (620 / 1100)
                elements.append(Paragraph(str(title), s["body"]))
                elements.append(Spacer(1, 4))
                elements.append(RLImage(bio, width=img_w, height=img_h))
                elements.append(Spacer(1, 10))
                if title == "Knowledge graph":
                    kg = section_dict(ar, "knowledge_graph_builder")
                    kn = kg.get("nodes") or []
                    if isinstance(kn, list) and kn:
                        elements.append(
                            Paragraph("Node details (context &amp; insights per node)", s["body"])
                        )
                        elements.append(Spacer(1, 4))
                        nrows = knowledge_graph_node_rows([x for x in kn if isinstance(x, dict)])
                        if nrows:
                            elements.append(
                                _make_table(
                                    ["Node ID", "Label", "Type", "Value", "Context", "Insights"],
                                    nrows,
                                    [
                                        0.85 * inch,
                                        1.0 * inch,
                                        0.65 * inch,
                                        0.55 * inch,
                                        1.95 * inch,
                                        1.45 * inch,
                                    ],
                                )
                            )
                        elements.append(Spacer(1, 10))
    except Exception as e:
        logger.warning("PDF charts section failed: %s", e)
        elements.append(Paragraph(f"Charts could not be generated: {e}", s["body_muted"]))
        elements.append(Spacer(1, 8))

    # ── KPI / Forecast Summary ──────────────────────────────
    forecasts = trend_data.get("forecasts") or []
    if forecasts:
        elements.append(Paragraph("KPI / Forecast Summary", s["section"]))
        kpi_headers = ["KPI / Metric", "Forecast", "Details"]
        kpi_rows: list[list[str]] = []
        for fc in forecasts[:15]:
            if isinstance(fc, dict):
                kpi_rows.append([
                    str(fc.get("metric") or fc.get("name") or fc.get("kpi", "—")),
                    str(fc.get("forecast") or fc.get("value") or fc.get("prediction", "—")),
                    str(fc.get("details") or fc.get("trend") or fc.get("direction", "")),
                ])
            else:
                kpi_rows.append([str(fc), "", ""])
        if kpi_rows:
            elements.append(_make_table(kpi_headers, kpi_rows, [1.8 * inch, 2.0 * inch, 2.4 * inch]))
            elements.append(Spacer(1, 10))

    # ── Insights ────────────────────────────────────────────
    insights_list = insight_data.get("insights") or []
    if insights_list:
        elements.append(Paragraph("Key Insights", s["section"]))
        for ins in insights_list[:12]:
            if isinstance(ins, dict):
                label = ins.get("title") or ins.get("insight") or "Insight"
                desc = ins.get("description") or ""
                impact = ins.get("impact") or ""
                elements.append(Paragraph(f"<b>{label}</b>", s["body"]))
                if desc:
                    elements.append(Paragraph(str(desc), s["body_muted"]))
                if impact:
                    elements.append(Paragraph(f"Impact: {impact}", s["body_muted"]))
                elements.append(Spacer(1, 4))
            else:
                elements.append(Paragraph(f"• {ins}", s["bullet"]))
        elements.append(Spacer(1, 6))

    # ── Recommendations ─────────────────────────────────────
    recommendations = insight_data.get("recommendations") or exec_data.get("next_actions") or []
    if recommendations:
        elements.append(Paragraph("Recommendations", s["section"]))
        rec_headers = ["Action", "Priority", "Confidence"]
        rec_rows: list[list[str]] = []
        for rec in recommendations[:15]:
            if isinstance(rec, dict):
                action = str(rec.get("action") or rec.get("recommendation") or rec.get("title", "—"))
                priority = str(rec.get("priority", "—"))
                conf = rec.get("confidence")
                conf_str = f"{float(conf):.0%}" if conf is not None else "—"
                rec_rows.append([action, priority, conf_str])
            else:
                rec_rows.append([str(rec), "—", "—"])
        if rec_rows:
            elements.append(_make_table(rec_headers, rec_rows, [3.6 * inch, 1.2 * inch, 1.4 * inch]))
            elements.append(Spacer(1, 10))

    # ── SWOT Summary ────────────────────────────────────────
    has_swot = any(swot_data.get(q) for q in ("strengths", "weaknesses", "opportunities", "threats"))
    if has_swot:
        elements.append(Paragraph("SWOT Analysis", s["section"]))
        for quadrant, label in [
            ("strengths", "Strengths"),
            ("weaknesses", "Weaknesses"),
            ("opportunities", "Opportunities"),
            ("threats", "Threats"),
        ]:
            items = swot_data.get(quadrant) or []
            if items:
                elements.append(Paragraph(f"<b>{label}</b>", s["body"]))
                for item in items[:5]:
                    txt = item if isinstance(item, str) else str(item.get("description", item) if isinstance(item, dict) else item)
                    elements.append(Paragraph(f"• {txt}", s["bullet"]))
                elements.append(Spacer(1, 4))
        elements.append(Spacer(1, 6))

    # ── Confidence Breakdown ────────────────────────────────
    conf_rows: list[list[str]] = []
    for aid, env in agent_outputs.items():
        conf = env.get("confidence")
        if conf is not None:
            st = env.get("status", "—")
            conf_rows.append([aid.replace("_", " ").title(), st, f"{float(conf):.0%}"])
    exec_conf = exec_data.get("confidence_statement")
    if isinstance(exec_conf, dict):
        overall = exec_conf.get("overall_confidence")
        basis = exec_conf.get("basis", "")
        if overall is not None:
            conf_rows.insert(0, ["Overall (Executive)", basis[:60] if basis else "—", f"{float(overall):.0%}"])

    if conf_rows:
        elements.append(Paragraph("Confidence Breakdown", s["section"]))
        elements.append(_make_table(
            ["Agent / Metric", "Status / Basis", "Confidence"],
            conf_rows,
            [2.6 * inch, 2.2 * inch, 1.4 * inch],
        ))
        elements.append(Spacer(1, 10))

    # ── Agent Activity Log ──────────────────────────────────
    activity = run_data.get("agent_activity") or []
    if activity:
        elements.append(Paragraph("Agent Activity Log", s["section"]))
        act_headers = ["Agent", "Stage", "Status", "Message"]
        act_rows: list[list[str]] = []
        for row in activity[:30]:
            if isinstance(row, dict):
                act_rows.append([
                    str(row.get("agent_id", "—")).replace("_", " ").title(),
                    str(row.get("stage", "—")),
                    str(row.get("status", "—")),
                    str(row.get("message", ""))[:80],
                ])
        if act_rows:
            elements.append(_make_table(act_headers, act_rows, [1.6 * inch, 1.0 * inch, 0.9 * inch, 2.7 * inch]))
            elements.append(Spacer(1, 10))

    # ── Warnings & Fix Suggestions ──────────────────────────
    warnings = report.get("warnings") or []
    fixes = report.get("fix_suggestions") or []
    if warnings or fixes:
        elements.append(Paragraph("Warnings &amp; Suggestions", s["section"]))
        for w in warnings[:10]:
            elements.append(Paragraph(f"⚠ {w}", s["bullet"]))
        for f in fixes[:10]:
            elements.append(Paragraph(f"→ {f}", s["bullet"]))
        elements.append(Spacer(1, 6))

    # ── Pipeline Log (last entries) ─────────────────────────
    plog = run_data.get("pipeline_log") or []
    if plog:
        elements.append(Paragraph("Pipeline Log (Recent)", s["section"]))
        for entry in plog[-10:]:
            elements.append(Paragraph(str(entry)[:120], s["body_muted"]))
        elements.append(Spacer(1, 8))

    # ── Build ───────────────────────────────────────────────
    if not elements:
        elements.append(Paragraph("No report data available for this run.", s["body"]))

    doc.build(elements, onFirstPage=_dark_bg, onLaterPages=_dark_bg)
    return buf.getvalue()
