-- Datalyze – auth schema extension
-- Safe to re-run: uses IF NOT EXISTS / ADD COLUMN IF NOT EXISTS

CREATE TABLE IF NOT EXISTS companies (
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash  VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_id     INTEGER REFERENCES companies(id) ON DELETE SET NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS setup_complete BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_path VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name  VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS job_title     VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW();
